FROM node:24-alpine AS builder
RUN apk add --no-cache libc6-compat git python3 py3-pip make g++ libusb-dev eudev-dev linux-headers

WORKDIR /app
COPY . .
WORKDIR /app/apps/web

RUN corepack enable
RUN yarn config set httpTimeout 300000
RUN yarn install --immutable
RUN yarn after-install

# These public variables are baked into the static web bundle at build time.
ARG NEXT_PUBLIC_WC_PROJECT_ID=4b6b77d337588564379b0ef8f3a5c479
ARG NEXT_PUBLIC_GATEWAY_URL_PRODUCTION=https://safe.doschain.com/cgw
ARG NEXT_PUBLIC_DEFAULT_MAINNET_CHAIN_ID=7979
ARG NEXT_PUBLIC_IS_OFFICIAL_HOST=false
ARG NEXT_PUBLIC_IS_PRODUCTION=true
ARG NEXT_PUBLIC_SAFE_VERSION=1.5.0
ARG NEXT_PUBLIC_BRAND_NAME="Safe on DOS"
ARG NEXT_PUBLIC_BRAND_LOGO=/images/dos-logo.svg
ARG NEXT_PUBLIC_APP_HOMEPAGE=https://safe.doschain.com

ENV NEXT_PUBLIC_WC_PROJECT_ID=$NEXT_PUBLIC_WC_PROJECT_ID
ENV NEXT_PUBLIC_GATEWAY_URL_PRODUCTION=$NEXT_PUBLIC_GATEWAY_URL_PRODUCTION
ENV NEXT_PUBLIC_DEFAULT_MAINNET_CHAIN_ID=$NEXT_PUBLIC_DEFAULT_MAINNET_CHAIN_ID
ENV NEXT_PUBLIC_IS_OFFICIAL_HOST=$NEXT_PUBLIC_IS_OFFICIAL_HOST
ENV NEXT_PUBLIC_IS_PRODUCTION=$NEXT_PUBLIC_IS_PRODUCTION
ENV NEXT_PUBLIC_SAFE_VERSION=$NEXT_PUBLIC_SAFE_VERSION
ENV NEXT_PUBLIC_BRAND_NAME=$NEXT_PUBLIC_BRAND_NAME
ENV NEXT_PUBLIC_BRAND_LOGO=$NEXT_PUBLIC_BRAND_LOGO
ENV NEXT_PUBLIC_APP_HOMEPAGE=$NEXT_PUBLIC_APP_HOMEPAGE

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
RUN yarn build

FROM node:24-alpine AS runtime

WORKDIR /app
RUN npm install --global serve@14.2.5 \
  && npm cache clean --force

COPY --from=builder --chown=node:node /app/apps/web/out ./out

USER node
ENV PORT=8080
EXPOSE 8080

CMD ["serve", "out", "-l", "8080"]
